# .github/workflows/main.yml

name: Schedule server ping
on:
  schedule:
    # Run at every 10 mins
    - cron: '*/10 * * * *'
jobs:
  build:
    name: Request server ping
    runs-on: ubuntu-latest
    steps:
      - name: Curl endpoint
        uses: indiesdev/curl@v1.1
        with:
          url: https://stremio-addon-debrid-search.onrender.com/manifest.json
          log-response: true
